//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverParse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OverParse.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always-on-top hotkey pressed.
        /// </summary>
        internal static string CON_AlwaysOnTop_Key {
            get {
                return ResourceManager.GetString("CON_AlwaysOnTop_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying UI settings.
        /// </summary>
        internal static string CON_ApplyUI {
            get {
                return ResourceManager.GetString("CON_ApplyUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a new log file ({0}), switching....
        /// </summary>
        internal static string CON_CheckForNewLog {
            get {
                return ResourceManager.GetString("CON_CheckForNewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing damageTimer.
        /// </summary>
        internal static string CON_damageTimer_INIT {
            get {
                return ResourceManager.GetString("CON_damageTimer_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug hotkey pressed.
        /// </summary>
        internal static string CON_DebugMenu_Key {
            get {
                return ResourceManager.GetString("CON_DebugMenu_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending encounter.
        /// </summary>
        internal static string CON_EndEncounter_Click_END {
            get {
                return ResourceManager.GetString("CON_EndEncounter_Click_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving last combatant list.
        /// </summary>
        internal static string CON_EndEncounter_Click_SAVE {
            get {
                return ResourceManager.GetString("CON_EndEncounter_Click_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter hotkey pressed.
        /// </summary>
        internal static string CON_EndEncounter_Key {
            get {
                return ResourceManager.GetString("CON_EndEncounter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending encounter (no log).
        /// </summary>
        internal static string CON_EndEncounterNoLog_Click_END {
            get {
                return ResourceManager.GetString("CON_EndEncounterNoLog_Click_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter hotkey (no log) pressed.
        /// </summary>
        internal static string CON_EndEncounterNoLog_Key {
            get {
                return ResourceManager.GetString("CON_EndEncounterNoLog_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing inactiveTimer.
        /// </summary>
        internal static string CON_inactiveTimer_INIT {
            get {
                return ResourceManager.GetString("CON_inactiveTimer_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing hotkeys.
        /// </summary>
        internal static string CON_Init_HotKeys {
            get {
                return ResourceManager.GetString("CON_Init_HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys failed to initialize.
        /// </summary>
        internal static string CON_Init_HotKeys_FAIL {
            get {
                return ResourceManager.GetString("CON_Init_HotKeys_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch method: {0}.
        /// </summary>
        internal static string CON_Launch {
            get {
                return ResourceManager.GetString("CON_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing default log.
        /// </summary>
        internal static string CON_LOG_INIT {
            get {
                return ResourceManager.GetString("CON_LOG_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinitializing log.
        /// </summary>
        internal static string CON_LOG_REINIT {
            get {
                return ResourceManager.GetString("CON_LOG_REINIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing logCheckTimer.
        /// </summary>
        internal static string CON_logCheckTimer_INIT {
            get {
                return ResourceManager.GetString("CON_logCheckTimer_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of MainWindow constructor.
        /// </summary>
        internal static string CON_MainWindow_END {
            get {
                return ResourceManager.GetString("CON_MainWindow_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempting to open {0}.
        /// </summary>
        internal static string CON_OpenRecentLog_Click {
            get {
                return ResourceManager.GetString("CON_OpenRecentLog_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window&apos;s off-screen, resetting.
        /// </summary>
        internal static string CON_outOfBounds {
            get {
                return ResourceManager.GetString("CON_outOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === UNHANDLED EXCEPTION ===.
        /// </summary>
        internal static string CON_Panic {
            get {
                return ResourceManager.GetString("CON_Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting.
        /// </summary>
        internal static string CON_ResetOverParse {
            get {
                return ResourceManager.GetString("CON_ResetOverParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished applying settings.
        /// </summary>
        internal static string CON_Setting_END {
            get {
                return ResourceManager.GetString("CON_Setting_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys in skill dict: {0}.
        /// </summary>
        internal static string CON_SKILL_COUNT {
            get {
                return ResourceManager.GetString("CON_SKILL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing skills.csv.
        /// </summary>
        internal static string CON_SKILL_PROCESS {
            get {
                return ResourceManager.GetString("CON_SKILL_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating skills.csv.
        /// </summary>
        internal static string CON_SKILL_Update {
            get {
                return ResourceManager.GetString("CON_SKILL_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.csv update failed: {0}.
        /// </summary>
        internal static string CON_SKILL_Update_FAIL {
            get {
                return ResourceManager.GetString("CON_SKILL_Update_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON version: {0} / Assembly version: {1}.
        /// </summary>
        internal static string CON_Update_DIFF {
            get {
                return ResourceManager.GetString("CON_Update_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update check: {0}.
        /// </summary>
        internal static string CON_Update_FAIL {
            get {
                return ResourceManager.GetString("CON_Update_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for release updates.
        /// </summary>
        internal static string CON_Update_INIT {
            get {
                return ResourceManager.GetString("CON_Update_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically ending an encounter.
        /// </summary>
        internal static string CON_UpdateForm {
            get {
                return ResourceManager.GetString("CON_UpdateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading settings.
        /// </summary>
        internal static string CON_Upgrade {
            get {
                return ResourceManager.GetString("CON_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERPARSE V.{0}.
        /// </summary>
        internal static string CON_VersionStamp {
            get {
                return ResourceManager.GetString("CON_VersionStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string CON_Window_Closing {
            get {
                return ResourceManager.GetString("CON_Window_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverParse Setup.
        /// </summary>
        internal static string UI_SetupTitle {
            get {
                return ResourceManager.GetString("UI_SetupTitle", resourceCulture);
            }
        }
    }
}
